# Generated by Django 2.2 on 2020-05-08 06:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0004_auto_20200508_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='pic2',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='pic3',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
