# Generated by Django 2.2 on 2020-05-08 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0003_auto_20200506_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='pic',
            new_name='pic1',
        ),
    ]
