# Generated by Django 3.0.6 on 2020-05-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0005_auto_20200508_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='pic4',
            field=models.ImageField(default=1, upload_to='images/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='pic2',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='image',
            name='pic3',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d'),
        ),
    ]
